### ISSUE TITLE
Enabling music, then sound crashes TSC

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#574]
Once again a music/sound problem for @kirbyfan64 :-)

The following sequence of steps crashes TSC with an `std::bad_alloc` exception:

1. Start the game
2. Go to the Options menu, there to the Audio menu
3. Disable music
4. Disable sound
5. Enable music
6. Enable sound
7. Crash.

Here's the GDB session:

~~~~~
% gdb ./TESTINSTALL/bin/tsc
GNU gdb (Gentoo 7.10.1 vanilla) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./TESTINSTALL/bin/tsc...done.
(gdb) r
Starting program: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/bin/tsc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Initializing resource manager and core classes
Game data directory: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc
User data directory: /home/quintus/.local/share/tsc
User cache directory: /home/quintus/.cache/tsc
User config directory: /home/quintus/.config/tsc
Initializing Package Manager
[New Thread 0x7fffe5140700 (LWP 6850)]
[New Thread 0x7ffff7f58700 (LWP 6851)]
Configuration file is '/home/quintus/.config/tsc/config.xml'.
Translation locale is de_DE.utf8
Translation support with gettext set to:
	Directory /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/translations
	Codeset: UTF-8
	Text domain: Secretchronicles
CEGUI log file is at '/home/quintus/.cache/tsc/cegui.log'.
Loading campaigns
Loaded campaign file: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/campaigns/tutorial.tsccpn
Loaded campaign file: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/campaigns/smc.tsccpn
Setting up level player
Loading levels
Applying preferences
CEGUI::UnknownObjectException in function 'CEGUI::Image& CEGUI::ImageManager::get(const CEGUI::String&) const' (/var/tmp/portage/dev-games/cegui-0.8.7/work/cegui-0.8.7/cegui/src/ImageManager.cpp:261) : Image not defined: hud_itembox_item
Warning : Object Furball did send Collision but doesn't exists in Manager
Warning : Object Furball did send Collision but doesn't exists in Manager
Warning : Object Furball did send Collision but doesn't exists in Manager
Warning : Object Furball did send Collision but doesn't exists in Manager
Warning : Object Furball did send Collision but doesn't exists in Manager
Warning : Object Armadillo did send Collision but doesn't exists in Manager
Warning : Object Armadillo did send Collision but doesn't exists in Manager
Warning : Object Armadillo did send Collision but doesn't exists in Manager
Warning : Object Armadillo did send Collision but doesn't exists in Manager
Warning : Object Armadillo did send Collision but doesn't exists in Manager
Warning : Object Armadillo did send Collision but doesn't exists in Manager
Warning : Object Krush did send Collision but doesn't exists in Manager
Warning : Object Krush did send Collision but doesn't exists in Manager
Warning : Object Spika did send Collision but doesn't exists in Manager
Warning : Object Spika did send Collision but doesn't exists in Manager
Warning : Object Spika did send Collision but doesn't exists in Manager
Warning : Object Spika did send Collision but doesn't exists in Manager
Warning : Object Spikeball did send Collision but doesn't exists in Manager
Warning : Object Spikeball did send Collision but doesn't exists in Manager
Warning : Object Larry did send Collision but doesn't exists in Manager
Warning : Object Larry did send Collision but doesn't exists in Manager
Warning : Object Larry did send Collision but doesn't exists in Manager
Warning : Object Doom Larry did send Collision but doesn't exists in Manager
Warning : Object Larry did send Collision but doesn't exists in Manager
Warning : Object Doom Larry did send Collision but doesn't exists in Manager
Warning : Object Beere did send Collision but doesn't exists in Manager
Warning : Object Beere did send Collision but doesn't exists in Manager
Warning : Object Beere did send Collision but doesn't exists in Manager
Warning : Object Beere did send Collision but doesn't exists in Manager
Warning : Object Beere did send Collision but doesn't exists in Manager
Warning : Object  did send Collision but doesn't exists in Manager
Warning : Object Kiste did send Collision but doesn't exists in Manager
Loading world from directory '/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/worlds/test_1'
Loading world from directory '/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/worlds/world_1'
Loading world from directory '/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/worlds/world_2'
Loading world from directory '/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/worlds/world_3'
Loading world from directory '/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/worlds/world_4'
Failed to load image "/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/pixmaps". Reason: Image not of any known type, or corrupt
Loaded level: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/levels/menu_brown_1.tsclvl
Preloading images and sounds...
Error loading image : /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/pixmaps/game/alex_l.png

Error loading GL surface image
Error loading image : /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/pixmaps/game/gold_m.png

Error loading GL surface image
Error loading image : /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/pixmaps/game/itembox.png

Error loading GL surface image
Done preloading images and sounds.
Error loading image : /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/pixmaps/menu/items/quit.png

Error loading GL surface image
[New Thread 0x7fffe1c3b700 (LWP 6852)]
[Thread 0x7fffe1c3b700 (LWP 6852) exited]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
0x00007ffff48c02e7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff48c02e7 in raise () from /lib64/libc.so.6
#1  0x00007ffff48c176a in abort () from /lib64/libc.so.6
#2  0x00007ffff51b59e5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#3  0x00007ffff51b36c6 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#4  0x00007ffff51b3731 in std::terminate() () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#5  0x00007ffff51b3967 in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#6  0x00007ffff51b3f8a in operator new(unsigned long) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#7  0x00007ffff5221779 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#8  0x00007ffff522259b in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#9  0x00007ffff5222660 in std::string::reserve(unsigned long) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#10 0x00007ffff5222778 in std::string::append(std::string const&) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
#11 0x00007ffff6a71544 in boost::filesystem::path::operator/=(boost::filesystem::path const&) () from /usr/lib64/libboost_filesystem.so.1.56.0
#12 0x00000000005844ae in boost::filesystem::operator/ (lhs=..., rhs=...) at /usr/include/boost/filesystem/path.hpp:648
#13 0x00000000006ca209 in TSC::cPackage_Manager::Find_Reading_Path (this=0xab26f0, dir=..., resource=..., extra_ext=std::vector of length 0, capacity 0)
    at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/filesystem/package_manager.cpp:528
#14 0x00000000006c8a5f in TSC::cPackage_Manager::Get_Music_Reading_Path (this=0xab26f0, music="") at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/filesystem/package_manager.cpp:352
#15 0x00000000006f3964 in TSC::cAudio::Play_Music (this=0xdb1a80, filename=..., loops=168, force=true, fadein_ms=32767) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/audio/audio.cpp:317
#16 0x00000000006f4b71 in TSC::cAudio::Update (this=0xdb1a80) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/audio/audio.cpp:651
#17 0x00000000006bf8c9 in TSC::Update_Game () at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/main.cpp:595
#18 0x00000000006be35d in main (argc=1, argv=0x7fffffffe498) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/main.cpp:207
(gdb) q
~~~~~

Valete,
Quintus

**Comment by kirbyfan64** [comment]
At this point, I'm just assuming the audio code is possessed. :/

**Comment by datahead8888** [comment]
It's probably just going to be a simple fix or two for the 2 issues open :)
Then it will finally be exorcised :)

**Comment by datahead8888** [comment]
I just got this seg fault and back trace after going back and forth between editing and playing my Desert Break In level.  It looks a little different from the one Quintus found, so I thought I'd include it here.  If I find more definitive steps to reproduce this instance, I will post it here or in another ticket.:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~c++
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff51d51db in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff51d51db in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000535e3d in boost::filesystem::path::path (this=0x7fffffffd3a0, 
    p=...) at /usr/include/boost/filesystem/path.hpp:132
#2  0x000000000057a469 in TSC::cAudio::NextMusicInfo::NextMusicInfo (
    this=0x7fffffffd3a0)
    at /home/datahead/TSC-SFML/TSC/tsc/src/audio/../audio/audio.hpp:92
#3  0x0000000000579cca in TSC::cAudio::Update (this=0xede540)
    at /home/datahead/TSC-SFML/TSC/tsc/src/audio/audio.cpp:649
#4  0x00000000006a2250 in TSC::Update_Game ()
    at /home/datahead/TSC-SFML/TSC/tsc/src/core/main.cpp:595
#5  0x00000000006a0d5c in main (argc=1, argv=0x7fffffffdf08)
    at /home/datahead/TSC-SFML/TSC/tsc/src/core/main.cpp:207
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by datahead8888** [comment]
@kirbyfan64 - do you know if you'll get time to work on the audio issues soon?  I've found that the audio issues can crash the game between loads of contributed levels on occasion, and the wrong music plays after a lemon power up finishes and/or when the level goal music completes.  The game also can crash after menu options are selected.

**Comment by Quintus** [comment]
Are you there, @kirbyfan64 ?

**Comment by kirbyfan64** [comment]
I died, and this is a ghost typing.

...

jk, would Saturday work?

**Comment by datahead8888** [comment]
> jk, would Saturday work?

It's whenever you get a chance, otherwise one of us would need to get it taken care of.

Thank you for letting us know - we appreciate the help.

**Comment by Quintus** [comment]
> I died, and this is a ghost typing.

Great, so now we have someone who can fight the ghosts in TSC's codebase. And while we are at it, could you please start haunting the person who wrote that code? :-P

**Comment by datahead8888** [comment]
> I died, and this is a ghost typing.

You know, we could use a ghost enemy :P
I'm sure you could make a cool sound effect for it, too :)

**Comment by kirbyfan64** [comment]
Huh...this is working perfectly for me. @Quintus sure you didn't leave out a little step or something?

**Comment by kirbyfan64** [comment]
@datahead8888 Your bug sounds like some kind of queue underflow. My guess is that, somehow, there was no music to play, but music was still technically "enabled". I pushed a commit that *might* fix it... *crosses fingers*

**Comment by datahead8888** [comment]
> Your bug sounds like some kind of queue underflow. My guess is that, somehow, there was no music to play, but music was still technically "enabled". I pushed a commit that might fix it... crosses fingers

I didn't have reproducible steps but wanted to share what I had.  I figured that if we succeed in fixing the reproducible issues with the menu selection crash and the incorrect music being played issue (#580), all other related issues may go away if we're lucky.  If one or two causes are creating the issues, it might fix the bulk of these issues.

**Comment by datahead8888** [comment]
> Huh...this is working perfectly for me. @Quintus sure you didn't leave out a little step or something?

Sorry, I missed this.  I'll retest this myself when I get a chance.  I will delete these last two posts.

**Comment by datahead8888** [comment]
I couldn't reproduce Quintus's crash with or without Kirbyfan64's latest commit.
I did however, produce this bug:
* Start the TSC executable
* Click "Start" on the main menu.  Choose the regular campaign, and press the "Enter" button.
* You will load the world map.  Start the first level.
* Go to the options menu
* Go to the audio tab
* Turn music off
* Turn sound off
* Turn music on
* Turn sound on
* You will find it is playing the title theme music, when it still should be playing the music for the first level in the game.

> @datahead8888 Your bug sounds like some kind of queue underflow.

I didn't have reproducible steps for the error I posted earlier, but I figured I'd share it in case we could examine the code for a fix.  An extra defense in the code will help us either way :)

**Comment by Quintus** [comment]
I was today unable to reproduce my own bug even without kirbyfan's
change applied. Appearently it was fixed meantime somehow, or it was due
to some temporary condition.

**Comment by datahead8888** [comment]
> I was today unable to reproduce my own bug even without kirbyfan's change applied. Appearently it was fixed meantime somehow, or it was due to some temporary condition.

A memory issue may not always cause a segfault.  Since, following the exact same steps you did, I saw a problem in which the wrong music played, there is probably still an issue in the audio system here.  #580 is probably caused by the same underlying issue.  The next step would be to ensure the correct music always plays for both of these tickets.

**Comment by datahead8888** [comment]
> I was today unable to reproduce my own bug even without kirbyfan's change applied. Appearently it was fixed meantime somehow, or it was due to some temporary condition.

Is there a chance a bad allocation may not always give an exception?  I know this is the case with segfaults.

Since, following the exact same steps you did, I saw a problem in which the wrong music played, there may still be an issue in the audio system here. #580 is probably caused by the same underlying issue. I think the next step would be to ensure the correct music always plays for both of these tickets.

**Comment by kirbyfan64** [comment]
I have pretty strong reason to believe the bug @datahead8888 found is the same one that @Quintus reported. Both revolved around playing the next song in the queue before necessary. @Quintus just crashed TSC because there was no "next song"; the queue was empty, and it screwed everything up.

**Comment by datahead8888** [comment]
I just tested, and the correct music played.  This looks fixed to me.
